//an array of objects, can use foreach function
const words = [
  { Word: "Planet", hint: "A large object that orbits a star" },
  { Word: "Guitar", hint: "A musical instrument with strings" },
  { Word: "Ocean", hint: "A vast body of salt water" },
  { Word: "Camera", hint: "A device used to take photographs" },
  { Word: "Bicycle", hint: "A two-wheeled vehicle powered by pedals" },
  { Word: "Library", hint: "A place with lots of books" },
  { Word: "Rainbow", hint: "A colorful arc in the sky" },
  { Word: "Elephant", hint: "A large animal with a trunk" },
  { Word: "Pencil", hint: "A tool used for writing or drawing" },
  { Word: "Laptop", hint: "A portable computer" },
  { Word: "Volcano", hint: "A mountain that can erupt" },
  { Word: "Jungle", hint: "A dense, tropical forest" },
  { Word: "Rocket", hint: "A vehicle used to travel in space" },
  { Word: "Soccer", hint: "A sport played with a round ball" },
  { Word: "Cookie", hint: "A small sweet baked treat" },
  { Word: "Puzzle", hint: "A game that requires solving" },
  { Word: "Mirror", hint: "A surface that reflects images" },
  { Word: "Ladder", hint: "A tool used for climbing up or down" },
  { Word: "Pirate", hint: "A person who robs ships at sea" },
  { Word: "Bridge", hint: "A structure built over a river or road" },
  { Word: "Candle", hint: "A source of light made of wax" },
  { Word: "Dragon", hint: "A mythical fire-breathing creature" },
  { Word: "Hammer", hint: "A tool used for pounding nails" },
  { Word: "Button", hint: "A small fastener on clothes" },
  { Word: "Tunnel", hint: "An underground passage" },
  { Word: "Castle", hint: "A large fortified building" },
  { Word: "Orange", hint: "A citrus fruit and a color" },
  { Word: "Gloves", hint: "Worn on hands for warmth or protection" },
  { Word: "Rocket", hint: "A space vehicle" },
  { Word: "Notebook", hint: "Used for writing notes" },
  { Word: "Trophy", hint: "A prize for winning" },
  { Word: "Sandwich", hint: "Food made with bread and filling" },
  { Word: "Penguin", hint: "A black and white flightless bird" },
  { Word: "Spider", hint: "An eight-legged creature that spins webs" },
  { Word: "Cactus", hint: "A prickly desert plant" },
  { Word: "Helmet", hint: "Protects your head" },
  { Word: "Island", hint: "Land surrounded by water" },
  { Word: "Basket", hint: "Used to carry or hold items" },
  { Word: "Pillow", hint: "Used to rest your head" },
  { Word: "Lemon", hint: "A sour yellow fruit" },
  { Word: "Clock", hint: "Tells the time" },
  { Word: "Wallet", hint: "Holds money and cards" },
  { Word: "Backpack", hint: "Worn on your back to carry things" },
  { Word: "Fireman", hint: "Someone who puts out fires" },
  { Word: "Kangaroo", hint: "An animal with a pouch" },
  { Word: "Whistle", hint: "A sound-making device" },
  { Word: "Mailbox", hint: "Holds incoming and outgoing letters" },
  { Word: "Robot", hint: "A machine that can perform tasks" },
  { Word: "Shovel", hint: "Used for digging" },
  { Word: "Giraffe", hint: "The tallest land animal" },
  { Word: "Moon", hint: "Earth’s natural satellite" },
];

// const words = [
//   {
//     Word: "Planet",
//     hint: "A large object that orbits a star",
//   },
//   {
//     Word: "Guitar",
//     hint: "A musical instrument with strings",
//   },
//   {
//     Word: "Ocean",
//     hint: "A vast body of salt water",
//   },
//   {
//     Word: "Camera",
//     hint: "A device used to take photographs",
//   },
//   {
//     Word: "Bicycle",
//     hint: "A two-wheeled vehicle powered by pedals",
//   },
// ];
